# ATELIER 1 DEEP LEARNING 



## Context:
Deep Learning

LAB 1: Artificial Neural Networks

Pr. ABNANE Ibtissam
A European bank noticed unusual churn rate (i.e. customers are leaving); they want to understand the problem so they can assess and address it. This European bank operates in three countries: France, Spain and Germany.
6 months ago, the bank took a sample of the customers (10000 customers), they measured customer ID, surname, credit score, geography, gender, age, tenure (How long they have been in the bank), balance, number of products they had (i.e. saving account, credit cards, loan...), estimated salary.
After 6 months, the bank checked if each customer left or stayed (exited column, 1: left, 0: stayed).

## Result:

“Churn_Modeling.csv”

## Objective: 

To look into the dataset to get insight on the churn rate. We will use ANNs to predict
if a customer will leave the bank after 6 months or not.


## 1- Loading data

In [ ]:
pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/86/a3/a6ffba31621a402d12b137e656814c7b8de2f796fa976acbe92f4602ebad/tensorflow-2.13.0-cp311-cp311-macosx_10_15_x86_64.whl.metadata
  Using cached tensorflow-2.13.0-cp311-cp311-macosx_10_15_x86_64.whl.metadata (3.2 kB)
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/01/e4/dc0a1dcc4e74e08d7abedab278c795eef54a224363bb18f5692f416d834f/absl_py-2.0.0-py3-none-any.whl.metadata
  Using cached absl_py-2.0.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Obtaining dependency information for flatbuffers>=23.1.21 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Usin

In [2]:
import numpy as np 
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.13.0'

In [4]:
dataset=pd.read_csv("Churn_Modelling.csv")
X=dataset.iloc[:, 3:-1].values
y=dataset.iloc[:,-1].values


In [5]:
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


## 2- Data prepocessing

In [6]:
# Label Encoding the "Gender" column

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])
print(X)

#One Hot Encodimg the "Geography" Column

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],
                     remainder='passthrough')

X=np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## 3- Split the dataset into to test/train

In [8]:
#Splitting the dataset into the Training and Test set

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,
                                               random_state=0)

In [9]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

## 4- Building the Neural Network 

In [11]:
# Part 2 - Building the ANN

#Initializing the ANN

ann=tf.keras.models.Sequential()

#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

#Adding the second hidden layer

ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))



## 5- Training the neural network

In [12]:
# Part 3 - Training the ANN

# Compiling the ANN

ann.compile(optimizer='adam',loss='binary_crossentropy',
            metrics=['accuracy'])

# Training the ANN on the Training set

ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5847 - accuracy: 0.7170
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4756 - accuracy: 0.8005
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4475 - accuracy: 0.8044
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4337 - accuracy: 0.8104
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4221 - accuracy: 0.8170
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4121 - accuracy: 0.8241
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4035 - accuracy: 0.8286
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3961 - accuracy: 0.8317
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3899 - accuracy: 0.8346
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3841 - accura

## 6- This ligne represents

In [13]:
print(ann.predict(scaler.transform([[1,0,0,600,1,40,3,60000,2,
                                     1,1,50000]])))

1/1 [==============================] - 0s 188ms/step
[[0.0305277]]


## 7- Confusion matrix

In [14]:
# Predicting the Test set results
y_pred=ann.predict(X_test)
y_pred=(y_pred > 0.5)

print(np.concatenate((y_pred.reshape(len(y_pred),1),
                      y_test.reshape(len(y_test),1)),1))



# Making the Confuion Matrix

from sklearn.metrics import confusion_matrix,accuracy_score

cm=confusion_matrix(y_test,y_pred)

print(cm)
accuracy_score(y_test,y_pred)

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
[[1518   77]
 [ 202  203]]


0.8605